import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { TabsContent } from "@/components/ui/tabs";
import type { AccountSettingsDraft } from "./AccountSettingsSheet";
import { ConflictBadge, HUMAN_STATUS_META, StatusBadge, VERIFICATION_META } from "./statusMeta";
import type { AccountSettings, AccountSettingsAdapter, LoginProofRule } from "./types";

type Run = (task: () => Promise<AccountSettings | void>) => Promise<void>;
export function HumanAccountTab({ settings, draft, patch, pathError, markError, pending, run, adapter }: {
  settings: AccountSettings; draft: AccountSettingsDraft; patch: (value: Partial<AccountSettingsDraft>) => void;
  pathError: string | null; markError: string | null; pending: boolean; run: Run; adapter: AccountSettingsAdapter;
}) {
  const [cookie, setCookie] = useState("");
  const [authorization, setAuthorization] = useState("");
  const canRegister = (cookie.trim() !== "" || authorization.trim() !== "") && !pending;
  return <TabsContent value="human" className="space-y-4 pt-4">
    <section className="space-y-3 rounded-lg border p-3"><h3 className="text-sm font-semibold">HUMAN 세션 상태</h3><dl className="grid gap-2 text-sm"><div className="flex justify-between gap-2"><dt className="text-muted-foreground">상태</dt><dd><StatusBadge meta={HUMAN_STATUS_META[settings.human.status]} /></dd></div><div className="flex justify-between gap-2"><dt className="text-muted-foreground">검증 출처</dt><dd><StatusBadge meta={VERIFICATION_META[settings.human.verificationSource]} /></dd></div><div className="flex justify-between gap-2"><dt className="text-muted-foreground">마지막 확인</dt><dd className="font-mono text-xs">{settings.human.lastCheckedLabel}</dd></div><div className="flex justify-between gap-2"><dt className="text-muted-foreground">자격 충돌</dt><dd>{settings.human.credentialConflict ? <ConflictBadge /> : "없음"}</dd></div></dl><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={pending || settings.human.status === "CAPTURING"} onClick={() => void run(() => adapter.reconnectHumanSession(settings.id))}>로그인 캡처 시작</Button><Button variant="outline" disabled={pending || settings.human.status !== "CAPTURING"} onClick={() => void run(() => adapter.finishHumanSession(settings.id))}>캡처 종료·확인</Button><Button variant="destructive" disabled={pending || settings.human.status === "UNVERIFIED" || settings.human.status === "REVOKED"} onClick={() => void run(() => adapter.revokeHumanSession(settings.id))}>세션 폐기</Button></div></section>
    <section className="space-y-3 rounded-lg border p-3"><h3 className="text-sm font-semibold">로그인 성공 검증 규칙</h3><div className="grid gap-2 sm:grid-cols-[7rem_1fr]"><div className="grid gap-1.5"><Label htmlFor="proof-method">method</Label><Select value={draft.proof.method} onValueChange={(value) => patch({ proof: { ...draft.proof, method: value as LoginProofRule["method"] } })}><SelectTrigger id="proof-method"><SelectValue /></SelectTrigger><SelectContent>{["GET", "HEAD", "POST"].map((method) => <SelectItem key={method} value={method}>{method}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-1.5"><Label htmlFor="proof-path">검증 요청 path</Label><Input id="proof-path" value={draft.proof.path} onChange={(event) => patch({ proof: { ...draft.proof, path: event.target.value } })} className="font-mono" /></div></div>{pathError && <p role="alert" className="text-xs text-destructive">{pathError}</p>}<div className="grid gap-1.5"><Label htmlFor="proof-mark">응답 표식</Label><Input id="proof-mark" value={draft.proof.responseMark} onChange={(event) => patch({ proof: { ...draft.proof, responseMark: event.target.value } })} className="font-mono" />{markError && <p role="alert" className="text-xs text-destructive">{markError}</p>}</div><p className="text-xs text-muted-foreground">둘 다 비우면 규칙을 삭제합니다. query·fragment와 자격 원문은 저장하지 않습니다.</p></section>
    <section className="space-y-3 rounded-lg border p-3"><h3 className="text-sm font-semibold">관측된 인증 요청 연결</h3><p className="text-xs text-muted-foreground">같은 서비스의 HUMAN 요청 중 Cookie 또는 Authorization이 있고 응답까지 남아 있는 항목만 선택할 수 있습니다.</p>{settings.candidates.length ? <div className="space-y-2">{settings.candidates.map((candidate) => <div key={candidate.id} className={`rounded-md border px-3 py-2 text-xs ${candidate.eligible ? "" : "opacity-60"}`}><div className="flex flex-wrap items-center gap-2"><span className="font-mono">{candidate.status}</span><span className="font-mono">{candidate.method} {candidate.path}</span><span>{candidate.hasCookie ? "Cookie" : ""}{candidate.hasCookie && candidate.hasAuthorization ? " + " : ""}{candidate.hasAuthorization ? "Authorization" : ""}</span><Button className="ml-auto" size="sm" variant="outline" disabled={!candidate.eligible || pending} onClick={() => void run(() => adapter.linkBurpRequest(settings.id, candidate.id))}>이 요청 연결</Button></div><p className="mt-1 text-muted-foreground">{candidate.eligible ? (candidate.markMatched ? "검증 표식도 일치" : "운영자 확인으로 연결") : candidate.reason}</p></div>)}</div> : <div className="rounded-md border px-3 py-2 text-xs"><p className="font-medium">연결 가능한 요청이 없습니다.</p><ul className="list-inside list-disc text-muted-foreground">{settings.candidateBlockReasons.map((reason) => <li key={reason}>{reason}</li>)}</ul></div>}</section>
    <section className="space-y-3 rounded-lg border p-3"><h3 className="text-sm font-semibold">세션 자격 직접 등록</h3><p className="text-xs text-muted-foreground">계정의 Cookie 또는 Authorization을 붙여넣어 이 신원의 재사용 세션을 바로 등록합니다(Autorize·AuthMatrix 방식). 같은 브라우저 순차 로그인의 자격 충돌을 우회하며, 원문은 메모리에만 두고 저장·로그·스냅샷하지 않습니다. 등록하면 즉시 `ACTIVE · 운영자 확인`이 되고, 토큰이 만료되면 첫 재전송의 401로 자동 강등됩니다.</p><div className="grid gap-1.5"><Label htmlFor="cred-cookie">Cookie</Label><Input id="cred-cookie" value={cookie} onChange={(event) => setCookie(event.target.value)} className="font-mono" placeholder="session=...; other=..." autoComplete="off" /></div><div className="grid gap-1.5"><Label htmlFor="cred-auth">Authorization</Label><Input id="cred-auth" value={authorization} onChange={(event) => setAuthorization(event.target.value)} className="font-mono" placeholder="Bearer ..." autoComplete="off" /></div><Button variant="outline" disabled={!canRegister} onClick={() => void run(async () => { const next = await adapter.registerCredential(settings.id, { cookie, authorization }); setCookie(""); setAuthorization(""); return next; })}>세션 자격 등록</Button></section>
  </TabsContent>;
}
